
/*************** FLIGHT ****************************************************/

 BEGIN

INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1000,6,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1001,6,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1002,6,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1003,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1004,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1005,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1006,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1007,6,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1008,6,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1009,6,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1010,6,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1011,6,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1012,6,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1013,6,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1014,6,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1015,6,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1016,6,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1017,6,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1018,6,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1019,6,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1020,6,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1021,6,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
	  VALUES (1022,5,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1023,5,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1024,5,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1025,5,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1026,8,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1027,8,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1028,8,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1029,8,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1030,3,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1031,3,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1032,3,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1033,8,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1034,8,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1035,8,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1036,7,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1037,7,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1038,7,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1039,7,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1040,5,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1041,5,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1042,8,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1043,8,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1044,8,'Sun')

INSERT INTO FLIGHT (Flight_number,Airline_company_id,Weekdays)
     VALUES (1045,4,'Sun')

END