
/*************** FLIGHT ****************************************************/

 BEGIN

INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1000,4,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1001,4,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1002,4,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1003,4,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1004,4,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1005,4,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1006,4,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1007,4,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1008,4,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1009,4,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1010,4,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1011,4,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1012,4,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1013,4,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1014,4,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1015,4,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1016,4,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1017,4,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1018,4,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1019,4,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1020,4,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1021,4,'Sun')

INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
  VALUES (1022,3,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1023,3,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1024,3,'Mon')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1025,3,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1026,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1027,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1028,6,'Tue')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1029,6,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1030,1,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1031,1,'Wed')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1032,1,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1033,6,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1034,6,'Thu')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1035,6,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1036,5,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1037,5,'Fri')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1038,5,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1039,5,'Sat')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1040,3,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1041,3,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1042,6,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1043,6,'Sun')
INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1044,6,'Sun')

INSERT INTO FLIGHT (Flight_number,Airline_id,Weekdays)
     VALUES (1045,2,'Sun')

END