
/***** LEG_INSTANCE- ARRIVAL TIME VALIDATION - CHECK CONSTRAINT ****************/
ALTER TABLE LEG_INSTANCE  WITH CHECK 
ADD CONSTRAINT ARRIVAL_TIME_VALIDATION  
CHECK  ((Arrival_time is null) or (Departure_time < Arrival_time))

GO

/********** FLIGHT -  WEEKDAYS VALIDATION -  CHECK CONSTRAINT **********/

ALTER TABLE FLIGHT ADD CONSTRAINT DAY_VALIDATION
CHECK (Weekdays IN ('Mon','Tue','Wed','Thu','Fri','Sat','Sun'));

GO

/********** SEAT_RESERVATION - CUSTOMER PHONE VALIDATION -  CHECK CONSTRAINT **********/
ALTER TABLE SEAT_RESERVATION  WITH CHECK ADD  CONSTRAINT CUSTOMER_PHONE_VALIDATION
CHECK  (Customer_phone like '5[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') 
GO

/********** FARE -  RESTRICTION VALIDATION -  CHECK CONSTRAINT **********/

ALTER TABLE FARE ADD CONSTRAINT RESTRICTION_VALIDATION
CHECK (Restriction IN ('Ekonomi','Bussines Class','First Class'));

GO