/*************** FLIGHT ****************************************************/

 BEGIN

 
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1000,'Pegasus','Mon')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1001,'Pegasus','Mon')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1002,'Pegasus','Mon')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1003,'Pegasus','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1004,'Pegasus','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1005,'Pegasus','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1006,'Pegasus','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1007,'Pegasus','Wed')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1008,'Pegasus','Wed')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1009,'Pegasus','Wed')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1010,'Pegasus','Thu')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1011,'Pegasus','Thu')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1012,'Pegasus','Thu')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1013,'Pegasus','Fri')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1014,'Pegasus','Fri')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1015,'Pegasus','Fri')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1016,'Pegasus','Sat')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1017,'Pegasus','Sat')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1018,'Pegasus','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1019,'Pegasus','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1020,'Pegasus','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1021,'Pegasus','Sun')

INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
  VALUES (1022,'Bora','Mon')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1023,'Bora','Mon')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1024,'Bora','Mon')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1025,'Bora','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1026,'THY','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1027,'THY','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1028,'THY','Tue')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1029,'THY','Wed')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1030,'AnadoluJet','Wed')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1031,'AnadoluJet','Wed')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1032,'AnadoluJet','Thu')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1033,'THY','Thu')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1034,'THY','Thu')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1035,'THY','Fri')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1036,'Sun Express','Fri')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1037,'Sun Express','Fri')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1038,'Sun Express','Sat')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1039,'Sun Express','Sat')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1040,'Bora','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1041,'Bora','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1042,'THY','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1043,'THY','Sun')
INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1044,'THY','Sun')

INSERT INTO FLIGHT (Flight_number,Airline,Weekdays)
     VALUES (1045,'Atlas','Sun')

END